"use client";

import { Epilogue, DM_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { RestaurantProvider } from "@/context/RestaurantContext";
import { NotificationProvider } from "@/context/NotificationContext";

const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const metadata = {
  title: "Plates Up - Restaurant POS and Digital Menu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${epilogue.className} ${dmSans.className}`}>
        <AuthProvider>
          <NotificationProvider>
            <RestaurantProvider>{children}</RestaurantProvider>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
